cat af.actionsheet.js >> allPlugins.js
cat af.css3animate.js >> allPlugins.js
cat af.passwordBox.js >> allPlugins.js
cat af.scroller.js >> allPlugins.js
cat af.selectBox.js >> allPlugins.js
cat af.touchEvents.js >> allPlugins.js
cat af.touchLayer.js >> allPlugins.js
cat af.popup.js >> allPlugins.js
#cat af.slidemenu.js >> allPlugins.js
#cat af.scrollScreen.js >> allPlugins.js
#cat af.desktopBrowsers.js >> allPlugins.js
#cat af.8tiles.js >> allPlugins.js
